# Generated by Django 2.2.2 on 2020-06-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='event_description',
        ),
        migrations.AddField(
            model_name='user',
            name='password_change_code',
            field=models.CharField(max_length=6, null=True, verbose_name='Код для смены пароля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(null=True, related_name='events', to='diplomv.Event', verbose_name='События пользователя'),
        ),
    ]
