# Generated by Django 2.2.2 on 2020-06-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomv', '0002_auto_20200616_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_change_password',
            field=models.BooleanField(null=True, verbose_name='Возможность сменить пароль'),
        ),
    ]
