# Generated by Django 2.2.2 on 2020-07-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomv', '0003_user_can_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/diplomv/avatar3x.png', null=True, upload_to='user_avatars/', verbose_name='Фото'),
        ),
    ]
