# Generated by Django 2.2.2 on 2020-07-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomv', '0005_auto_20200706_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/diplomv/user_avatars/default_avatar.png', null=True, upload_to='user_avatars/', verbose_name='Фото'),
        ),
    ]
